#!/usr/bin/env bash
set -euo pipefail
#  _____                 _        ____  _        _            _
# |_   _|__   __ _  __ _| | ___  / ___|| |_ __ _| |_ _   _ __| |__   __ _ _ __
#   | |/ _ \ / _` |/ _` | |/ _ \ \___ \| __/ _` | __| | | / _` | '_ \ / _` | '__|
#   | | (_) | (_| | (_| | |  __/  ___) | || (_| | |_| |_| \__,_| |_) | (_| | |
#   |_|\___/ \__, |\__, |_|\___| |____/ \__\__,_|\__|\__,_|\__,_|_.__/ \__,_|_|
#            |___/ |___/
#
# Toggle the statusbar used by Shayar OS. 

qs -c caelestia ipc call drawers toggle bar 2>/dev/null || caelestia shell -d
