#!/usr/bin/env bash
set -uo pipefail

case "${1:-}" in
    d|--delete)
        caelestia clipboard -d
    ;;
    w|--wipe)    
        cliphist wipe
    ;;
    *)
        caelestia clipboard
    ;;
esac
