#!/usr/bin/env bash
set -uo pipefail

case "${1:-}" in
    d)
        cliphist list | rofi -dmenu -replace -config ~/.config/rofi/config-cliphist.rasi | cliphist delete || true
    ;;
    w)    
        cliphist wipe
    ;;
    *)
        cliphist list | rofi -dmenu -replace -config ~/.config/rofi/config-cliphist.rasi | cliphist decode | wl-copy || true
    ;;
esac
