#!/usr/bin/env bash
set -euo pipefail
#                              __    __
#   ___  __ _  ___ ____  ___  / /__ / /_
#  / _ \/  ' \/ _ `/ _ \/ _ \/ / -_) __/
# /_//_/_/_/_/\_,_/ .__/ .__/_/\__/\__/
#                /_/  /_/
#
if [[ "${1:-}" == "stop" ]]; then
    killall nm-applet 2>/dev/null || true
elif [[ "${1:-}" == "toggle" ]]; then
    if pgrep -x "nm-applet" >/dev/null; then
        killall nm-applet 2>/dev/null || true
        echo "Stopped"
    else
        nm-applet --indicator &
        echo "Running"
    fi
else
    nm-applet --indicator &
fi
