
$background = rgba(12131bff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(302f39ff)

$inverse_primary = rgba(3f5e96ff)

$inverse_surface = rgba(e4e1eeff)

$on_background = rgba(e4e1eeff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(062f64ff)

$on_primary_container = rgba(0c3268ff)

$on_primary_fixed = rgba(001a40ff)

$on_primary_fixed_variant = rgba(25467cff)

$on_secondary = rgba(1f3700ff)

$on_secondary_container = rgba(9dc071ff)

$on_secondary_fixed = rgba(102000ff)

$on_secondary_fixed_variant = rgba(324f0bff)

$on_surface = rgba(e4e1eeff)

$on_surface_variant = rgba(c4c6d1ff)

$on_tertiary = rgba(68000fff)

$on_tertiary_container = rgba(6e0011ff)

$on_tertiary_fixed = rgba(410006ff)

$on_tertiary_fixed_variant = rgba(8c1620ff)

$outline = rgba(8e909bff)

$outline_variant = rgba(43474fff)

$primary = rgba(acc7ffff)

$primary_container = rgba(7e9cd8ff)

$primary_fixed = rgba(d7e2ffff)

$primary_fixed_dim = rgba(acc7ffff)

$scrim = rgba(000000ff)

$secondary = rgba(aed280ff)

$secondary_container = rgba(324f0bff)

$secondary_fixed = rgba(c9ef9aff)

$secondary_fixed_dim = rgba(aed280ff)

$shadow = rgba(000000ff)

$source_color = rgba(acc7ffff)

$surface = rgba(12131bff)

$surface_bright = rgba(393842ff)

$surface_container = rgba(1f1f28ff)

$surface_container_high = rgba(292932ff)

$surface_container_highest = rgba(34343dff)

$surface_container_low = rgba(1b1b24ff)

$surface_container_lowest = rgba(0d0d16ff)

$surface_dim = rgba(12131bff)

$surface_tint = rgba(acc7ffff)

$surface_variant = rgba(34343dff)

$tertiary = rgba(ffb3b0ff)

$tertiary_container = rgba(ff6c6cff)

$tertiary_fixed = rgba(ffdad8ff)

$tertiary_fixed_dim = rgba(ffb3b0ff)


