-- Generated from design-tokens.json -- DO NOT EDIT
dt = {}
dt["colors"] = {}
dt["colors"]["background"] = "#12131b"
dt["colors"]["error"] = "#ffb4ab"
dt["colors"]["error_container"] = "#93000a"
dt["colors"]["inverse_on_surface"] = "#302f39"
dt["colors"]["inverse_primary"] = "#3f5e96"
dt["colors"]["inverse_surface"] = "#e4e1ee"
dt["colors"]["on_background"] = "#e4e1ee"
dt["colors"]["on_error"] = "#690005"
dt["colors"]["on_error_container"] = "#ffdad6"
dt["colors"]["on_primary"] = "#062f64"
dt["colors"]["on_primary_container"] = "#0c3268"
dt["colors"]["on_primary_fixed"] = "#001a40"
dt["colors"]["on_primary_fixed_variant"] = "#25467c"
dt["colors"]["on_secondary"] = "#1f3700"
dt["colors"]["on_secondary_container"] = "#9dc071"
dt["colors"]["on_secondary_fixed"] = "#102000"
dt["colors"]["on_secondary_fixed_variant"] = "#324f0b"
dt["colors"]["on_surface"] = "#e4e1ee"
dt["colors"]["on_surface_variant"] = "#c4c6d1"
dt["colors"]["on_tertiary"] = "#68000f"
dt["colors"]["on_tertiary_container"] = "#6e0011"
dt["colors"]["on_tertiary_fixed"] = "#410006"
dt["colors"]["on_tertiary_fixed_variant"] = "#8c1620"
dt["colors"]["outline"] = "#8e909b"
dt["colors"]["outline_variant"] = "#43474f"
dt["colors"]["primary"] = "#acc7ff"
dt["colors"]["primary_container"] = "#7e9cd8"
dt["colors"]["primary_fixed"] = "#d7e2ff"
dt["colors"]["primary_fixed_dim"] = "#acc7ff"
dt["colors"]["scrim"] = "#000000"
dt["colors"]["secondary"] = "#aed280"
dt["colors"]["secondary_container"] = "#324f0b"
dt["colors"]["secondary_fixed"] = "#c9ef9a"
dt["colors"]["secondary_fixed_dim"] = "#aed280"
dt["colors"]["shadow"] = "#000000"
dt["colors"]["source_color"] = "#acc7ff"
dt["colors"]["surface"] = "#12131b"
dt["colors"]["surface_bright"] = "#393842"
dt["colors"]["surface_container"] = "#1f1f28"
dt["colors"]["surface_container_high"] = "#292932"
dt["colors"]["surface_container_highest"] = "#34343d"
dt["colors"]["surface_container_low"] = "#1b1b24"
dt["colors"]["surface_container_lowest"] = "#0d0d16"
dt["colors"]["surface_dim"] = "#12131b"
dt["colors"]["surface_tint"] = "#acc7ff"
dt["colors"]["surface_variant"] = "#34343d"
dt["colors"]["tertiary"] = "#ffb3b0"
dt["colors"]["tertiary_container"] = "#ff6c6c"
dt["colors"]["tertiary_fixed"] = "#ffdad8"
dt["colors"]["tertiary_fixed_dim"] = "#ffb3b0"
dt["typography"] = {}
dt["typography"]["mono_family"] = "JetBrainsMono Nerd Font"
dt["typography"]["mono_size"] = 12
dt["typography"]["ui_family"] = "Fira Sans"
dt["typography"]["ui_size"] = 11
dt["typography"]["ui_semibold"] = "Fira Sans Semibold"
dt["typography"]["rubik_bold"] = "Rubik Bold"
dt["typography"]["jetbrains_bold"] = "JetBrains Mono Bold"
dt["typography"]["clock_format"] = "JetBrains Mono Bold 12"
dt["typography"]["clock_date_format"] = "Rubik Bold 12"
dt["typography"]["rofi_font"] = "Fira Sans 11"
dt["typography"]["hyprlock_font"] = "Fira Sans Semibold"
dt["typography"]["hyprlock_clock_size"] = 70
dt["typography"]["hyprlock_user_size"] = 20
dt["typography"]["icon_theme"] = "Tela-circle-dracula"
dt["typography"]["cursor_theme"] = "Bibata-Modern-Ice"
dt["typography"]["cursor_size"] = 24
dt["typography"]["waybar_icon_size"] = 18
dt["typography"]["waybar_font_family"] = "'Rubik', 'JetBrains Mono', 'Font Awesome 6 Free', 'Font Awesome 6 Brands', sans-serif"
dt["typography"]["waybar_pango_font"] = "Rubik"
dt["typography"]["swaync_icon_size"] = 48
dt["typography"]["waybar_font_size"] = 13
dt["typography"]["waybar_icon_font_size"] = 18
dt["typography"]["waybar_battery_font_size"] = 14
dt["typography"]["sddm_font"] = "Fira Sans"
dt["typography"]["fastfetch_color"] = "blue"
dt["spacing"] = {}
dt["spacing"]["rounding"] = 10
dt["spacing"]["rounding_power"] = 2
dt["spacing"]["gaps_in"] = 10
dt["spacing"]["gaps_out"] = 20
dt["spacing"]["border_size"] = 2
dt["spacing"]["shadow_range"] = 32
dt["spacing"]["shadow_render_power"] = 2
dt["spacing"]["shadow_color"] = "rgba(00000050)"
dt["spacing"]["blur_size"] = 4
dt["spacing"]["blur_passes"] = 4
dt["spacing"]["blur_vibrancy"] = 0.1696
dt["spacing"]["waybar_margin_top"] = 8
dt["spacing"]["waybar_margin_left"] = 24
dt["spacing"]["waybar_margin_right"] = 24
dt["spacing"]["waybar_spacing"] = 12
dt["spacing"]["waybar_padding_x"] = 18
dt["spacing"]["waybar_padding_y"] = 4
dt["spacing"]["waybar_pill_padding_x"] = 20
dt["spacing"]["waybar_pill_padding_y"] = 4
dt["spacing"]["waybar_center_padding_x"] = 14
dt["spacing"]["waybar_center_padding_y"] = 4
dt["spacing"]["waybar_pill_margin_x"] = 6
dt["spacing"]["waybar_pill_margin_y"] = 4
dt["spacing"]["waybar_workspace_margin"] = 8
dt["spacing"]["waybar_workspace_spacing"] = 12
dt["spacing"]["waybar_workspace_size"] = 18
dt["spacing"]["waybar_icon_padding"] = 10
dt["spacing"]["waybar_divider_padding"] = 6
dt["spacing"]["hyprlock_input_width"] = 200
dt["spacing"]["hyprlock_input_height"] = 50
dt["spacing"]["hyprlock_dots_size"] = 0.33
dt["spacing"]["hyprlock_dots_spacing"] = 0.15
dt["spacing"]["hyprlock_dots_rounding"] = -1
dt["spacing"]["hyprlock_outline_thickness"] = 3
dt["spacing"]["hyprlock_fade_timeout"] = 1000
dt["spacing"]["hyprlock_input_rounding"] = 10
dt["spacing"]["hyprlock_input_position_x"] = 0
dt["spacing"]["hyprlock_input_position_y"] = -20
dt["spacing"]["hyprlock_input_shadow_passes"] = 10
dt["spacing"]["hyprlock_input_shadow_size"] = 20
dt["spacing"]["hyprlock_input_shadow_boost"] = 1.6
dt["spacing"]["hyprlock_clock_position_x"] = -50
dt["spacing"]["hyprlock_clock_position_y"] = 20
dt["spacing"]["hyprlock_clock_shadow_passes"] = 5
dt["spacing"]["hyprlock_clock_shadow_size"] = 10
dt["spacing"]["hyprlock_user_position_x"] = -50
dt["spacing"]["hyprlock_user_position_y"] = 120
dt["spacing"]["hyprlock_user_shadow_passes"] = 5
dt["spacing"]["hyprlock_user_shadow_size"] = 10
dt["spacing"]["hyprlock_image_size"] = 280
dt["spacing"]["hyprlock_image_rounding"] = 40
dt["spacing"]["hyprlock_image_border_size"] = 4
dt["spacing"]["hyprlock_image_position_x"] = 0
dt["spacing"]["hyprlock_image_position_y"] = 200
dt["spacing"]["hyprlock_image_shadow_passes"] = 10
dt["spacing"]["hyprlock_image_shadow_size"] = 20
dt["spacing"]["hyprlock_image_shadow_boost"] = 1.6
dt["spacing"]["hyprlock_combined_input_size"] = "200, 50"
dt["spacing"]["hyprlock_combined_input_position"] = "0, -20"
dt["spacing"]["hyprlock_combined_clock_position"] = "-50, 20"
dt["spacing"]["hyprlock_combined_user_position"] = "-50, 120"
dt["spacing"]["hyprlock_combined_image_position"] = "0, 200"
dt["spacing"]["swaync_control_center_width"] = 360
dt["spacing"]["swaync_control_center_height"] = 700
dt["spacing"]["swaync_control_center_margin_top"] = 11
dt["spacing"]["swaync_control_center_margin_right"] = 3
dt["spacing"]["swaync_notification_width"] = 360
dt["spacing"]["swaync_notification_body_image_height"] = 100
dt["spacing"]["swaync_notification_body_image_width"] = 200
dt["spacing"]["swaync_timeout"] = 4
dt["spacing"]["swaync_timeout_low"] = 2
dt["spacing"]["swaync_timeout_critical"] = 6
dt["spacing"]["swaync_transition_time"] = 200
dt["spacing"]["swaync_border_radius"] = 12
dt["spacing"]["swaync_padding_large"] = 40
dt["spacing"]["swaync_padding_medium"] = 12
dt["spacing"]["swaync_margin_small"] = 10
dt["spacing"]["rofi_window_width"] = "56em"
dt["spacing"]["rofi_window_height"] = "35em"
dt["spacing"]["rofi_border_radius"] = "24px"
dt["spacing"]["rofi_border_width"] = "1px"
dt["spacing"]["rofi_padding"] = "20px"
dt["spacing"]["rofi_element_padding"] = "15px"
dt["spacing"]["rofi_element_radius"] = "2em"
dt["spacing"]["rofi_list_radius"] = "16px"
dt["spacing"]["rofi_settings_border_radius"] = "2em"
dt["spacing"]["rofi_settings_border_width"] = "2px"
dt["spacing"]["rofi_popup_width"] = "22em"
dt["spacing"]["rofi_popup_padding"] = "1em"
dt["spacing"]["rofi_popup_element_radius"] = "1.1em"
dt["spacing"]["rofi_popup_selected_radius"] = "1.5em"
dt["spacing"]["volume_slider_width"] = 200
dt["spacing"]["volume_slider_height"] = 45
dt["spacing"]["volume_slider_x_offset"] = 250
dt["spacing"]["volume_slider_y_position"] = 55
dt["spacing"]["volume_slider_border_radius"] = 12
dt["spacing"]["volume_slider_padding"] = 10
dt["spacing"]["volume_slider_bar_radius"] = 6
dt["spacing"]["volume_slider_bar_min_height"] = 6
dt["spacing"]["volume_slider_thumb_size"] = 14
dt["spacing"]["slurp_border_width"] = 1
dt["spacing"]["slurp_background_color"] = "#00000080"
dt["spacing"]["slurp_border_color"] = "#888888ff"
dt["spacing"]["sddm_clock_size"] = 48
dt["spacing"]["sddm_button_font_size"] = 14
dt["spacing"]["sddm_input_width"] = 250
dt["spacing"]["sddm_input_height"] = 40
dt["spacing"]["sddm_input_radius"] = 8
dt["spacing"]["sddm_layout_spacing"] = 20
dt["spacing"]["sddm_inner_spacing"] = 10
dt["spacing"]["sddm_blur"] = 32
dt["spacing"]["sddm_brightness"] = -0.1
dt["spacing"]["sddm_saturation"] = -0.2
dt["opacity"] = {}
dt["opacity"]["active"] = 1.0
dt["opacity"]["inactive"] = 0.9
dt["opacity"]["fullscreen"] = 1.0
dt["opacity"]["waybar_pill_background"] = 0.5
dt["opacity"]["waybar_pill_hover_background"] = 0.7
dt["opacity"]["waybar_workspace_inactive"] = 0.7
dt["opacity"]["waybar_workspace_hover"] = 1.0
dt["opacity"]["waybar_border_alpha"] = 0.05
dt["opacity"]["waybar_border_hover_alpha"] = 0.1
dt["opacity"]["waybar_shadow_alpha"] = 0.3
dt["opacity"]["waybar_shadow_hover_alpha"] = 0.4
dt["opacity"]["waybar_glow_alpha"] = 0.05
dt["opacity"]["waybar_glow_hover_alpha"] = 0.1
dt["opacity"]["waybar_tertiary_alpha"] = 0.85
dt["opacity"]["waybar_divider_alpha"] = 0.2
dt["opacity"]["kitty_background"] = 0.7
dt["opacity"]["swaync_background_alpha"] = 0.5
dt["opacity"]["swaync_notification_bg_alpha"] = 0.8
dt["opacity"]["swaync_button_hover_alpha"] = 0.5
dt["opacity"]["volume_slider_bg_alpha"] = 0.9
dt["opacity"]["volume_slider_border_alpha"] = 0.08
dt["opacity"]["volume_slider_track_alpha"] = 0.1
dt["animation"] = {}
dt["animation"]["bezier_linear"] = "0 0, 1 1"
dt["animation"]["bezier_md3_standard"] = "0.2 0, 0 1"
dt["animation"]["bezier_md3_decel"] = "0.05 0.7, 0.1 1"
dt["animation"]["bezier_md3_accel"] = "0.3 0, 0.8 0.15"
dt["animation"]["bezier_overshot"] = "0.05 0.9, 0.1 1.1"
dt["animation"]["bezier_crazyshot"] = "0.1 1.5, 0.76 0.92"
dt["animation"]["bezier_hyprnostretch"] = "0.05 0.9, 0.1 1.0"
dt["animation"]["bezier_menu_decel"] = "0.1 1, 0 1"
dt["animation"]["bezier_menu_accel"] = "0.38 0.04, 1 0.07"
dt["animation"]["bezier_easeInOutCirc"] = "0.85 0, 0.15 1"
dt["animation"]["bezier_easeOutCirc"] = "0 0.55, 0.45 1"
dt["animation"]["bezier_easeOutExpo"] = "0.16 1, 0.3 1"
dt["animation"]["bezier_softAcDecel"] = "0.26 0.26, 0.15 1"
dt["animation"]["bezier_md2"] = "0.4 0, 0.2 1"
dt["animation"]["speed_window"] = 3
dt["animation"]["speed_border"] = 10
dt["animation"]["speed_fade"] = 3
dt["animation"]["speed_layers_in"] = 3
dt["animation"]["speed_layers_out"] = 1.6
dt["animation"]["speed_fade_layers_in"] = 2
dt["animation"]["speed_fade_layers_out"] = 4.5
dt["animation"]["speed_workspace"] = 5
dt["animation"]["speed_special_workspace"] = 3
dt["animation"]["waybar_transition"] = "0.3s cubic-bezier(0.4, 0, 0.2, 1)"
dt["animation"]["waybar_hover_transition"] = "0.2s ease"
dt["animation"]["swaync_transition"] = "200ms"
dt["animation"]["swaync_transition_css"] = "250ms"
dt["shadow"] = {}
dt["shadow"]["waybar"] = "0 10px 30px -5px"
dt["shadow"]["waybar_hover"] = "0 10px 30px -5px"
dt["shadow"]["waybar_glow"] = "0 0 15px"
dt["shadow"]["waybar_hover_glow"] = "0 0 20px"
dt["shadow"]["swaync_notification"] = "0 1px 10px 1px"
dt["kitty"] = {}
dt["kitty"]["font_family"] = "JetBrainsMono Nerd Font"
dt["kitty"]["font_size"] = 12
dt["kitty"]["initial_window_width"] = 950
dt["kitty"]["initial_window_height"] = 500
dt["kitty"]["window_padding_width"] = 10
dt["kitty"]["scrollback_lines"] = 2000
dt["kitty"]["cursor_blink_interval"] = 0.5
dt["kitty"]["cursor_stop_blinking_after"] = 1.0
dt["kitty"]["background_opacity"] = 0.7
dt["gtk"] = {}
dt["gtk"]["theme_name"] = "Adwaita"
dt["gtk"]["icon_theme_name"] = "Tela-circle-dracula"
dt["gtk"]["font_name"] = "Fira Sans Semi-Bold 11"
dt["gtk"]["cursor_theme_name"] = "Bibata-Modern-Ice"
dt["gtk"]["cursor_theme_size"] = 24
dt["gtk"]["dark_mode_preference"] = 1
dt["quickshell"] = {}
dt["quickshell"]["panel_width"] = 180
dt["quickshell"]["panel_width_wide"] = 320
dt["quickshell"]["panel_width_vol"] = 200
dt["quickshell"]["panel_radius"] = 40
dt["quickshell"]["net_panel_radius"] = 24
dt["quickshell"]["bt_panel_radius"] = 24
dt["quickshell"]["vol_panel_radius"] = 12
dt["quickshell"]["panel_bg_alpha"] = 0.95
dt["quickshell"]["blur_strength"] = 0.7
dt["quickshell"]["blur_saturation"] = 0.0
dt["quickshell"]["gradient_top_alpha"] = 0.12
dt["quickshell"]["gradient_mid_alpha"] = 0.04
dt["quickshell"]["gradient_lower_alpha"] = 0.01
dt["quickshell"]["border_alpha"] = 0.2
dt["quickshell"]["border_width"] = 1
dt["quickshell"]["shadow_alpha"] = 0.4
dt["quickshell"]["shadow_blur"] = 24
dt["quickshell"]["button_spacing"] = 12
dt["quickshell"]["button_width"] = 130
dt["quickshell"]["button_height"] = 56
dt["quickshell"]["row_height"] = 48
dt["quickshell"]["label_height"] = 30
dt["quickshell"]["label_radius"] = 15
dt["quickshell"]["label_alpha"] = 0.88
dt["quickshell"]["icon_size"] = 18
dt["quickshell"]["icon_circle_size"] = 52
dt["quickshell"]["primary_alpha"] = 0.9
dt["quickshell"]["hover_border_alpha"] = 0.5
dt["quickshell"]["font_size_label"] = 13
dt["quickshell"]["font_size_small"] = 11
dt["quickshell"]["waybar_clearance"] = 42
dt["quickshell"]["calendar_width"] = 320
dt["quickshell"]["calendar_height"] = 380
dt["quickshell"]["calendar_margin_left"] = 12
dt["quickshell"]["calendar_radius"] = 24
dt["quickshell"]["calendar_inner_margin"] = 20
dt["quickshell"]["calendar_spacing"] = 10
dt["quickshell"]["calendar_grid_spacing"] = 3
dt["quickshell"]["font_size_title"] = 16
dt["quickshell"]["font_size_body"] = 12
dt["quickshell"]["hover_scale"] = 1.05
dt["quickshell"]["list_inner_margin"] = 16
dt["quickshell"]["list_row_margin"] = 8
dt["quickshell"]["list_row_spacing"] = 10
dt["quickshell"]["list_column_spacing"] = 8
dt["quickshell"]["header_spacing"] = 8
dt["quickshell"]["toggle_button_size"] = 32
dt["quickshell"]["list_icon_size"] = 14
dt["quickshell"]["separator_alpha"] = 0.1
dt["quickshell"]["row_hover_alpha"] = 0.15
dt["quickshell"]["row_selected_alpha"] = 0.1
dt["quickshell"]["row_connected_alpha"] = 0.12
dt["quickshell"]["row_border_alpha"] = 0.3
dt["quickshell"]["icon_circle_alpha"] = 0.6
dt["quickshell"]["track_alpha"] = 0.1
dt["quickshell"]["thumb_size"] = 14
dt["quickshell"]["bar_radius"] = 6
dt["quickshell"]["bar_min_height"] = 6
dt["quickshell"]["welcome_panel_width"] = 420
dt["quickshell"]["welcome_panel_radius"] = 24
