-- Generated from design-tokens.json -- DO NOT EDIT
dt = {}
dt["colors"] = {}
dt["colors"]["background"] = "#121318"
dt["colors"]["error"] = "#ffb4ab"
dt["colors"]["error_container"] = "#93000a"
dt["colors"]["inverse_on_surface"] = "#2f3036"
dt["colors"]["inverse_primary"] = "#4a5c92"
dt["colors"]["inverse_surface"] = "#e3e2e9"
dt["colors"]["on_background"] = "#e3e2e9"
dt["colors"]["on_error"] = "#690005"
dt["colors"]["on_error_container"] = "#ffdad6"
dt["colors"]["on_primary"] = "#192e60"
dt["colors"]["on_primary_container"] = "#dbe1ff"
dt["colors"]["on_primary_fixed"] = "#001849"
dt["colors"]["on_primary_fixed_variant"] = "#314578"
dt["colors"]["on_secondary"] = "#2a3042"
dt["colors"]["on_secondary_container"] = "#dde2f9"
dt["colors"]["on_secondary_fixed"] = "#151b2c"
dt["colors"]["on_secondary_fixed_variant"] = "#414659"
dt["colors"]["on_surface"] = "#e3e2e9"
dt["colors"]["on_surface_variant"] = "#c5c6d0"
dt["colors"]["on_tertiary"] = "#422741"
dt["colors"]["on_tertiary_container"] = "#ffd6f9"
dt["colors"]["on_tertiary_fixed"] = "#2b122b"
dt["colors"]["on_tertiary_fixed_variant"] = "#5a3d58"
dt["colors"]["outline"] = "#8f909a"
dt["colors"]["outline_variant"] = "#45464f"
dt["colors"]["primary"] = "#b3c5ff"
dt["colors"]["primary_container"] = "#314578"
dt["colors"]["primary_fixed"] = "#dbe1ff"
dt["colors"]["primary_fixed_dim"] = "#b3c5ff"
dt["colors"]["scrim"] = "#000000"
dt["colors"]["secondary"] = "#c1c6dd"
dt["colors"]["secondary_container"] = "#414659"
dt["colors"]["secondary_fixed"] = "#dde2f9"
dt["colors"]["secondary_fixed_dim"] = "#c1c6dd"
dt["colors"]["shadow"] = "#000000"
dt["colors"]["source_color"] = "#6e85c8"
dt["colors"]["surface"] = "#121318"
dt["colors"]["surface_bright"] = "#38393f"
dt["colors"]["surface_container"] = "#1e1f25"
dt["colors"]["surface_container_high"] = "#292a2f"
dt["colors"]["surface_container_highest"] = "#33343a"
dt["colors"]["surface_container_low"] = "#1a1b21"
dt["colors"]["surface_container_lowest"] = "#0d0e13"
dt["colors"]["surface_dim"] = "#121318"
dt["colors"]["surface_tint"] = "#b3c5ff"
dt["colors"]["surface_variant"] = "#45464f"
dt["colors"]["tertiary"] = "#e1bbdc"
dt["colors"]["tertiary_container"] = "#5a3d58"
dt["colors"]["tertiary_fixed"] = "#ffd6f9"
dt["colors"]["tertiary_fixed_dim"] = "#e1bbdc"
dt["typography"] = {}
dt["typography"]["mono_family"] = "GeistMono Nerd Font"
dt["typography"]["ui_family"] = "Geist"
dt["typography"]["ui_size"] = 11
dt["typography"]["ui_semibold"] = "Geist SemiBold"
dt["typography"]["icon_font_family"] = "Symbols Nerd Font Mono"
dt["typography"]["rofi_font"] = "Geist, Symbols Nerd Font Mono 11"
dt["typography"]["hyprlock_font"] = "Geist SemiBold"
dt["typography"]["hyprlock_clock_size"] = 70
dt["typography"]["hyprlock_user_size"] = 20
dt["typography"]["icon_theme"] = "Tela-circle-dracula"
dt["typography"]["cursor_theme"] = "Bibata-Modern-Ice"
dt["typography"]["cursor_size"] = 24
dt["typography"]["waybar_icon_size"] = 18
dt["typography"]["waybar_pango_font"] = "Geist"
dt["typography"]["waybar_font_size"] = 13
dt["typography"]["waybar_icon_font_size"] = 18
dt["typography"]["sddm_font"] = "Geist"
dt["typography"]["fastfetch_color"] = "blue"
dt["spacing"] = {}
dt["spacing"]["rounding"] = 10
dt["spacing"]["rounding_power"] = 2
dt["spacing"]["gaps_in"] = 10
dt["spacing"]["gaps_out"] = 20
dt["spacing"]["border_size"] = 2
dt["spacing"]["shadow_range"] = 32
dt["spacing"]["shadow_color"] = "rgba(00000050)"
dt["spacing"]["blur_size"] = 4
dt["spacing"]["blur_passes"] = 4
dt["spacing"]["blur_vibrancy"] = 0.1696
dt["spacing"]["waybar_margin_top"] = 8
dt["spacing"]["waybar_margin_left"] = 24
dt["spacing"]["waybar_margin_right"] = 24
dt["spacing"]["waybar_spacing"] = 12
dt["spacing"]["waybar_pill_padding_x"] = 20
dt["spacing"]["waybar_pill_margin_x"] = 6
dt["spacing"]["waybar_icon_padding"] = 10
dt["spacing"]["hyprlock_dots_size"] = 0.33
dt["spacing"]["hyprlock_dots_spacing"] = 0.15
dt["spacing"]["hyprlock_dots_rounding"] = -1
dt["spacing"]["hyprlock_outline_thickness"] = 3
dt["spacing"]["hyprlock_fade_timeout"] = 1000
dt["spacing"]["hyprlock_input_rounding"] = 10
dt["spacing"]["hyprlock_input_shadow_passes"] = 10
dt["spacing"]["hyprlock_input_shadow_size"] = 20
dt["spacing"]["hyprlock_input_shadow_boost"] = 1.6
dt["spacing"]["hyprlock_clock_shadow_passes"] = 5
dt["spacing"]["hyprlock_clock_shadow_size"] = 10
dt["spacing"]["hyprlock_user_shadow_passes"] = 5
dt["spacing"]["hyprlock_user_shadow_size"] = 10
dt["spacing"]["hyprlock_image_size"] = 280
dt["spacing"]["hyprlock_image_rounding"] = 40
dt["spacing"]["hyprlock_image_border_size"] = 4
dt["spacing"]["hyprlock_image_shadow_passes"] = 10
dt["spacing"]["hyprlock_image_shadow_size"] = 20
dt["spacing"]["hyprlock_image_shadow_boost"] = 1.6
dt["spacing"]["hyprlock_combined_input_size"] = "200, 50"
dt["spacing"]["hyprlock_combined_input_position"] = "0, -20"
dt["spacing"]["hyprlock_combined_clock_position"] = "-50, 20"
dt["spacing"]["hyprlock_combined_user_position"] = "-50, 120"
dt["spacing"]["hyprlock_combined_image_position"] = "0, 200"
dt["spacing"]["swaync_border_radius"] = 12
dt["spacing"]["swaync_padding_medium"] = 12
dt["spacing"]["swaync_margin_small"] = 10
dt["spacing"]["rofi_window_width"] = "56em"
dt["spacing"]["rofi_window_height"] = "35em"
dt["spacing"]["rofi_border_radius"] = "24px"
dt["spacing"]["rofi_border_width"] = "1px"
dt["spacing"]["rofi_padding"] = "20px"
dt["spacing"]["rofi_element_radius"] = "2em"
dt["spacing"]["rofi_list_radius"] = "16px"
dt["spacing"]["rofi_popup_width"] = "22em"
dt["spacing"]["rofi_popup_padding"] = "1em"
dt["spacing"]["rofi_popup_element_radius"] = "1.1em"
dt["spacing"]["rofi_popup_selected_radius"] = "1.5em"
dt["spacing"]["sddm_clock_size"] = 72
dt["spacing"]["sddm_input_width"] = 300
dt["spacing"]["sddm_input_height"] = 48
dt["spacing"]["sddm_input_radius"] = 14
dt["spacing"]["sddm_layout_spacing"] = 24
dt["opacity"] = {}
dt["opacity"]["active"] = 1.0
dt["opacity"]["inactive"] = 0.9
dt["opacity"]["fullscreen"] = 1.0
dt["opacity"]["swaync_background_alpha"] = 1
dt["opacity"]["swaync_notification_bg_alpha"] = 1
dt["opacity"]["swaync_button_hover_alpha"] = 0.5
dt["animation"] = {}
dt["animation"]["bezier_linear"] = "0 0, 1 1"
dt["animation"]["bezier_md3_standard"] = "0.2 0, 0 1"
dt["animation"]["bezier_md3_decel"] = "0.05 0.7, 0.1 1"
dt["animation"]["bezier_md3_accel"] = "0.3 0, 0.8 0.15"
dt["animation"]["bezier_overshot"] = "0.05 0.9, 0.1 1.1"
dt["animation"]["bezier_crazyshot"] = "0.1 1.5, 0.76 0.92"
dt["animation"]["bezier_hyprnostretch"] = "0.05 0.9, 0.1 1.0"
dt["animation"]["bezier_menu_decel"] = "0.1 1, 0 1"
dt["animation"]["bezier_menu_accel"] = "0.38 0.04, 1 0.07"
dt["animation"]["bezier_easeInOutCirc"] = "0.85 0, 0.15 1"
dt["animation"]["bezier_easeOutCirc"] = "0 0.55, 0.45 1"
dt["animation"]["bezier_easeOutExpo"] = "0.16 1, 0.3 1"
dt["animation"]["bezier_softAcDecel"] = "0.26 0.26, 0.15 1"
dt["animation"]["bezier_md2"] = "0.4 0, 0.2 1"
dt["animation"]["speed_window"] = 3
dt["animation"]["speed_border"] = 10
dt["animation"]["speed_fade"] = 3
dt["animation"]["speed_layers_in"] = 3
dt["animation"]["speed_layers_out"] = 1.6
dt["animation"]["speed_fade_layers_in"] = 2
dt["animation"]["speed_fade_layers_out"] = 4.5
dt["animation"]["speed_workspace"] = 5
dt["animation"]["speed_special_workspace"] = 3
dt["animation"]["swaync_transition"] = "200ms"
dt["kitty"] = {}
dt["kitty"]["font_family"] = "GeistMono Nerd Font"
dt["kitty"]["font_size"] = 12
dt["kitty"]["initial_window_width"] = 950
dt["kitty"]["initial_window_height"] = 500
dt["kitty"]["window_padding_width"] = 10
dt["kitty"]["scrollback_lines"] = 2000
dt["kitty"]["cursor_blink_interval"] = 0.5
dt["kitty"]["cursor_stop_blinking_after"] = 1.0
dt["kitty"]["background_opacity"] = 0.7
dt["quickshell"] = {}
dt["quickshell"]["panel_width"] = 180
dt["quickshell"]["panel_width_wide"] = 380
dt["quickshell"]["panel_width_vol"] = 200
dt["quickshell"]["panel_radius"] = 40
dt["quickshell"]["net_panel_radius"] = 24
dt["quickshell"]["bt_panel_radius"] = 24
dt["quickshell"]["vol_panel_radius"] = 12
dt["quickshell"]["panel_bg_alpha"] = 1
dt["quickshell"]["border_alpha"] = 0.2
dt["quickshell"]["border_width"] = 1
dt["quickshell"]["shadow_alpha"] = 0.4
dt["quickshell"]["shadow_blur"] = 24
dt["quickshell"]["button_spacing"] = 12
dt["quickshell"]["button_width"] = 130
dt["quickshell"]["button_height"] = 56
dt["quickshell"]["row_height"] = 48
dt["quickshell"]["label_height"] = 30
dt["quickshell"]["label_radius"] = 15
dt["quickshell"]["label_alpha"] = 0.88
dt["quickshell"]["icon_size"] = 18
dt["quickshell"]["icon_circle_size"] = 52
dt["quickshell"]["primary_alpha"] = 0.9
dt["quickshell"]["hover_border_alpha"] = 0.5
dt["quickshell"]["font_size_label"] = 13
dt["quickshell"]["font_size_small"] = 11
dt["quickshell"]["waybar_clearance"] = 42
dt["quickshell"]["calendar_width"] = 320
dt["quickshell"]["calendar_height"] = 380
dt["quickshell"]["calendar_margin_left"] = 12
dt["quickshell"]["calendar_radius"] = 24
dt["quickshell"]["calendar_inner_margin"] = 20
dt["quickshell"]["calendar_spacing"] = 10
dt["quickshell"]["font_size_title"] = 16
dt["quickshell"]["font_size_body"] = 12
dt["quickshell"]["list_inner_margin"] = 16
dt["quickshell"]["list_row_margin"] = 8
dt["quickshell"]["list_row_spacing"] = 10
dt["quickshell"]["list_column_spacing"] = 8
dt["quickshell"]["toggle_button_size"] = 32
dt["quickshell"]["list_icon_size"] = 14
dt["quickshell"]["separator_alpha"] = 0.1
dt["quickshell"]["row_hover_alpha"] = 0.15
dt["quickshell"]["icon_circle_alpha"] = 0.6
dt["quickshell"]["thumb_size"] = 14
dt["quickshell"]["bar_radius"] = 6
dt["quickshell"]["bar_min_height"] = 6
dt["quickshell"]["welcome_panel_width"] = 420
dt["quickshell"]["welcome_panel_radius"] = 24
dt["quickshell"]["badge_alpha"] = 0.15
dt["quickshell"]["badge_paired_alpha"] = 0.1
dt["quickshell"]["badge_border_alpha"] = 0.3
