cursor #e4e1ee
cursor_text_color #c4c6d1

foreground            #e4e1ee
background            #12131b
selection_foreground  #1f3700
selection_background  #aed280
url_color             #acc7ff

# black
color8   #34343d
color0   #12131b

# red
color1   #ffb4ab
color9   #ffb3b0

# green
color2   #aed280
color10  #c9ef9a

# yellow
color3   #c9ef9a
color11  #aed280

# blue
color4  #acc7ff
color12 #7e9cd8

# magenta
color5   #ffb3b0
color13  #ffdad8

# cyan
color6  #e4e1ee
color14 #ffb3b0

# white
color15  #e4e1ee
color7 #393842
