# Shayar Configuration
# Source this file in any script to access all settings.
#   source "${HOME}/.config/shayar/settings/shayar.conf"
#
# After changing values, scripts pick them up automatically.

# Application choices
TERMINAL="kitty"
BROWSER="firefox"
FILE_MANAGER="nautilus --new-window"
CALCULATOR="flatpak run org.gnome.Calculator"  # If you change this, update class match in shayar.lua window rule
EMOJI_PICKER="flatpak run com.tomjwatson.Emote"
SYSTEM_MONITOR="missioncenter"
BLUETOOTH_MANAGER="blueman-manager"

# Wallpaper
WALLPAPER_FOLDER="${HOME}/.config/shayar/wallpapers"
WALLPAPER_TRANSITION="simple"
BLUR="50x30"

# Screenshot
SCREENSHOT_FILENAME='screenshot_$(date +%Y%m%d_%H%M%S).jpg'
SCREENSHOT_FOLDER="${HOME}/Pictures"
